
create table kb_categories (
dc_id integer generated by default as identity,
description varchar(111),
jpaVersion integer not null,
dc_name varchar(63) not null,
dc_public boolean,
primary key (dc_id)
);

create table kb_questions (
dc_id integer generated by default as identity,
creation_date timestamp not null,
jpaVersion integer not null,
last_modified_date timestamp not null,
number_of_replies integer,
question_preview varchar(255),
dc_status integer not null,
dc_title varchar(111),
author_id integer,
category_id integer not null,
last_modified_by_id integer,
questioncontent_id integer not null,
primary key (dc_id)
);

create table kb_questions_tags (
question_id integer not null,
tag_id integer not null
);

create table kb_replies (
dc_id integer generated by default as identity,
creation_date timestamp not null,
highlighted boolean,
jpaVersion integer not null,
last_modified_date timestamp not null,
author_id integer,
last_modified_by_id integer,
question_id integer not null,
replycontent_id integer not null,
primary key (dc_id)
);

create table kb_tags (
dc_id integer generated by default as identity,
description varchar(111),
jpaVersion integer not null,
dc_name varchar(63) not null,
dc_status integer not null,
category_id integer not null,
primary key (dc_id)
);

create table kb_text_content (
dc_id integer generated by default as identity,
content varchar(5242880) not null,
jpaVersion integer not null,
primary key (dc_id)
);

create table kb_usercategory (
category_id integer not null,
user_id integer not null,
admin_in_category boolean,
user_disabled_in_category boolean,
following_all_tags boolean,
hidden_in_dashboard boolean,
jpaVersion integer not null,
primary key (category_id, user_id)
);

create table kb_usercategory_question (
category_id integer not null,
user_id integer not null,
question_id integer not null
);

create table kb_usercategory_tag (
category_id integer not null,
user_id integer not null,
tag_id integer not null
);

create table kb_users (
dc_id integer not null,
user_disabled boolean,
jpaVersion integer not null,
notification_disabled boolean,
primary key (dc_id)
);

create unique index UK_KB_CATEGORIES on kb_categories (dc_name);

create unique index UK_KB_TAGS on kb_tags (dc_name, category_id);

alter table kb_questions
add constraint FK_KB_QUESTION_AUTHOR
foreign key (author_id)
references core_user;

alter table kb_questions
add constraint FK_KB_QUESTION_CATEGORY
foreign key (category_id)
references kb_categories;

alter table kb_questions
add constraint FK_KB_QUESTION_CREATOR
foreign key (last_modified_by_id)
references core_user;

alter table kb_questions
add constraint FK_KB_QUESTION_TEXTCONTENT
foreign key (questioncontent_id)
references kb_text_content;

alter table kb_questions_tags
add constraint FK_KB_TAGS_QUESTIONS
foreign key (tag_id)
references kb_tags;

alter table kb_questions_tags
add constraint FK_KB_QUESTIONS_TAGS
foreign key (question_id)
references kb_questions;

alter table kb_replies
add constraint FK_KB_REPLIES_AUTHOR
foreign key (author_id)
references core_user;

alter table kb_replies
add constraint FK_KB_REPLIES_MODIFIEDBY
foreign key (last_modified_by_id)
references core_user;

alter table kb_replies
add constraint FK_KB_REPLIES_QUESTION
foreign key (question_id)
references kb_questions;

alter table kb_replies
add constraint FK_KB_REPLY_TEXTCONTENT
foreign key (replycontent_id)
references kb_text_content;

alter table kb_tags
add constraint FK_KB_TAGS_CATEGORY
foreign key (category_id)
references kb_categories;

alter table kb_usercategory
add constraint FK7sgpt7u6jpcl99kbj0k09atdi
foreign key (category_id)
references kb_categories;

alter table kb_usercategory
add constraint FKiucq04gy2dc3dffftr11c6ue2
foreign key (user_id)
references kb_users;

alter table kb_usercategory_question
add constraint FK_KB_QUESTION_USERCATEGORY
foreign key (question_id)
references kb_questions;

alter table kb_usercategory_question
add constraint FK_KB_USERCATEGORY_QUESTION
foreign key (category_id, user_id)
references kb_usercategory;

alter table kb_usercategory_tag
add constraint FK_KB_TAG_USERCATEGORY
foreign key (tag_id)
references kb_tags;

alter table kb_usercategory_tag
add constraint FK_KB_USERCATEGORY_TAG
foreign key (category_id, user_id)
references kb_usercategory;

alter table kb_users
add constraint FK_KB_USER
foreign key (dc_id)
references core_user;
